name: Poimandres Offline Vault
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build R3F & Drei
        # We build them sequentially in one runner to avoid variable collisions
        # And we use the 'next build' command directly to see the logs if it fails
        run: |
          export OUTPUT=export
          export HOME_REDIRECT=/getting-started/introduction
          
          # Build R3F
          export MDX=docs/react-three-fiber
          export NEXT_PUBLIC_LIBNAME="React Three Fiber"
          pnpm build
          mv out out-r3f

          # Build Drei
          export MDX=docs/drei
          export NEXT_PUBLIC_LIBNAME="Drei"
          pnpm build
          mv out out-drei

      - name: Upload Docs
        uses: actions/upload-artifact@v4
        with:
          name: PMNDRS-Docs
          path: |
            out-r3f
            out-drei
