name: Scrape PMNDRS Docs
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Install Static Scraper
        run: sudo apt-get install wget

      - name: Mirror R3F
        run: |
          wget --mirror --convert-links --adjust-extension --page-requisites \
          --no-parent https://docs.pmnd.rs/react-three-fiber/
          
      - name: Mirror Drei
        run: |
          wget --mirror --convert-links --adjust-extension --page-requisites \
          --no-parent https://docs.pmnd.rs/drei/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PMNDRS-Offline-Mirror
          path: docs.pmnd.rs/
